# Generated by Django 2.1.7 on 2019-04-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_auto_20190415_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzeimage',
            name='user',
        ),
    ]
