# Generated by Django 2.1.7 on 2019-04-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_remove_analyzeimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzeimage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='analyzeimage',
            name='uploaded_at',
        ),
    ]
